# Generated by Django 3.2.7 on 2021-09-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('altura', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('diametro', models.CharField(max_length=50)),
                ('periodo_rotacion', models.CharField(max_length=50)),
                ('periodo_orbitacion', models.CharField(max_length=50)),
                ('poblacion', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('productor', models.CharField(max_length=120)),
                ('texto_intro', models.CharField(max_length=800)),
                ('fecha', models.DateField()),
                ('personajes', models.ManyToManyField(blank=True, related_name='peliculas', to='starwars.Personaje')),
                ('planetas', models.ManyToManyField(blank=True, related_name='peliculas', to='starwars.Planeta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
