# Generated by Django 3.2.7 on 2021-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='pelicula_id',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
